# Generated by Django 4.1.2 on 2023-04-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Countdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
